FemtoCleaner ran to update deprecations
First, I ran my forked FemtoCleaner (https://github.com/aminya/FemtoCleaner.jl)) locally to update the deprecated syntax.

However, as I have written in here in Julia forum (https://discourse.julialang.org/t/add-and-develope-an-unregistered-local-package/25632), I can not add the package, apparently, because of the old Tk.jl image package used. Or maybe there is an issue somewhere else.

Now in Julia 1.1.1 there are better image packages we can use. Otherwise, We should use https://github.com/JuliaGraphics/Gtk.jl isntead

When I try to add it I get this error:

]add C:\\Users\\username\\Documents\\GitHub\\MatlabCompat.jl

  Updating registry at `C:\Users\username\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `C:\\Users\\username\\Documents\\GitHub\\MatlabCompat.jl`
  Updating git-repo `C:\\Users\\username\\Documents\\GitHub\\MatlabCompat.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Tk [4225ea8a]:
 Tk [4225ea8a] log:
 ├─possible versions are: [0.0.1, 0.2.0-0.2.17, 0.3.0-0.3.8, 0.4.0, 0.5.0-0.5.2] or uninstalled
 ├─restricted to versions 0.0.0-* by MatlabCompat [54e369d6], leaving only versions [0.0.1, 0.2.0-0.2.17, 0.3.0-0.3.8, 0.4.0, 0.5.0-0.5.2]
 │ └─MatlabCompat [54e369d6] log:
 │   ├─possible versions are: 0.1.2 or uninstalled
 │   └─MatlabCompat [54e369d6] is fixed to version 0.1.2+
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions lef